spring:
  application:
    name: sb-security-facebook-login

security:
  oauth2:
    client:      client-id: app_id
      client-secret: app_secret
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth 
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form 
    resource:      user-info-uri: https://graph.facebook.com/me

server:  port: 8080
#  servlet:#    context-path: /sb-security-facebook-login

logging:
  level:
    root: info
    poc.springboot: debug
  file: /var/tmp/log/apps/sb-security-facebook-login/sb-security-facebook-login
  
