spring:
  application:
    name: springboot-security
#  security:
#    user:
#      name: ashish
#      password: nopass

server:  port: 8080
#  servlet:#    context-path: /springboot-security

logging:
  level:
    root: info
    poc.springboot: debug
  file: /var/tmp/log/apps/springboot-security/springboot-security
  
