spring:
  application:
    name: sb-security-jwt
#  security:
#    user:
#      name: ashish
#      password: nopass

server:  port: 8080
#  servlet:#    context-path: /sb-security-jwt

logging:
  level:
    root: info
    poc.springboot: debug
  file: /var/tmp/log/apps/sb-security-jwt/sb-security-jwt
  
