spring:
  application:
    name: spring-security-facebook-login

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: app_id
            client-secret: app_secret

server:  port: 8080
#  servlet:#    context-path: /spring-security-facebook-login

logging:
  level:
    root: info
    poc.springboot: debug
  file: /var/tmp/log/apps/spring-security-facebook-login/spring-security-facebook-login
  
