spring:
 application:
  name: apps-status

server:  port: 7272
  servlet:    context-path: /apps-status

logging:
  level:
    root: info
  file: /var/tmp/log/apps/apps-status/apps-status
  
app:
  commands:
    - /opt/ngs/ashishb/bash/apps-status/apps-status.sh
    #- cd
    #- /opt/ngs/ashishb/bash/apps-status
    #- bash
    #- apps-status-remote1.sh